.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tgr-refile 1  "tgr-refile " 
.SH NAME
tgr\-refile \- Refile org trees that have tags that match a pattern
.SH SYNOPSIS
\fBtgr refile\fR [\fB\-n\fR|\fB\-\-no\-pager\fR] [\fB\-s\fR|\fB\-\-strict\fR] [\fB\-i\fR|\fB\-\-include\fR] [\fB\-e\fR|\fB\-\-exclude\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATTERN\fR> [\fIOUTPUT FILE\fR] 
.SH DESCRIPTION
Refile org trees that have tags that match a pattern
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-no\-pager\fR
Print the contents to stdout instead of pager
.TP
\fB\-s\fR, \fB\-\-strict\fR
Match the pattern strictly or loosely
.TP
\fB\-i\fR, \fB\-\-include\fR=\fIINCLUDE\fR
Override config by including files that match <PATTERN>
.TP
\fB\-e\fR, \fB\-\-exclude\fR=\fIEXCLUDE\fR
Override config by excluding files that match <PATTERN>
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATTERN\fR>
Pattern to find Org trees to refile
.TP
[\fIOUTPUT FILE\fR]
Name of the output file. If not given, output is paged or printed to the standard output
