.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tgr-sed 1  "tgr-sed " 
.SH NAME
tgr\-sed \- A wrapper around the `sed` cli utility to safely manipulate tags
.SH SYNOPSIS
\fBtgr sed\fR [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fITAG\fR> <\fIREPLACEMENT\fR> 
.SH DESCRIPTION
A wrapper around the `sed` cli utility to safely manipulate tags
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print additional information about substitutions
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITAG\fR>
The tag to be substituted. Note that this command will perform a substitution only on an exact match
.TP
<\fIREPLACEMENT\fR>
The replacement
